config/routes.rb
Rails.application.routes.draw do
 

  root 'static_pages#home'

  resources :corsairs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corsair.rb
class Corsair < ApplicationRecord
	validates :likeness,  acceptance: { accept: ['kebab', 'hummus'] }
	validates :firstname, :age, presence: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
end

app/controllers/corsairs_controller.rb
class CorsairsController < ApplicationController
  def index
  	@corsairs = Corsair.all
  end

  def new
  end

  def create
  	@corsair = Corsair.create(corsair_params)
  	redirect_to @corsair
  end

  def edit
  	@corsair = Corsair.find(params[:id])
  end

  def update
  	@corsair = Corsair.find(params[:id])
  	@corsair.update(corsair_params)
  	redirect_to corsairs_path
  	
  end

  def show
  	@corsair = Corsair.find(params[:id])
  end

  def destroy
  	@corsair = Corsair.find(params[:id])
  	@corsair.destroy
  	redirect_to corsairs_path

  	
  end
end

private

    def corsair_params

        params.require(:corsair).permit( :firstname, :age, :bio, :slack_handle, :github_handle)
        
    end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corsairs_helper.rb
module CorsairsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/corsairs/edit.html.erb
<h1>Modifier mes informations</h1>

<%=form_tag corsair_path(@corsair), method: :put do %>
  
<%= label_tag 'firstname', 'Firstname'%>
<%= text_field_tag 'corsair[firstname]'%>

<%= label_tag 'age', 'Age:'%>
<%= text_field_tag 'corsair[age]'%>

<%= label_tag 'bio', 'Bio:'%>
<%= text_field_tag 'corsair[bio]'%>

<%= label_tag 'slack_handle', 'Slack_handle:'%>
<%= text_field_tag 'corsair[slack_handle]'%>

<%= label_tag 'github_handle', 'Github_handle:'%>
<%= text_field_tag 'corsair[github_handle]'%>

<%= submit_tag "Mettre à jour", class: "btn btn-lg btn-primary"%>


<%end%>

<%= link_to "Supprimer mon compte", corsair_path(@corsair), method: :delete , data: { confirm: 'Are you sure?' }, class: "btn btn-lg btn-danger"%>
<%= link_to "Je ne souhaite plus modifier mon compte", corsairs_path, class: "btn btn-lg btn-success"%>

app/views/corsairs/index.html.erb
<h1>Ces moussaillons nous ont rejoint</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Age</th>
  </tr>

  <% @corsairs.each do |corsair| %>
    <tr>
      <td><%= corsair.firstname %></td>
      <td><%= corsair.age %></td>
      <td><%= link_to "Voir" , corsair_path(corsair) %> </td>
      
    </tr>
  <% end %>
</table>
</br>
<%= link_to "S'inscrire" , new_corsair_path, class: "btn btn-lg btn-primary" %>

app/views/corsairs/new.html.erb
<h1>Inscription</h1>

<%=form_tag (corsairs_path) do %>
  
<%= label_tag 'firstname', 'Firstname:'%>
<%= text_field_tag 'corsair[firstname]'%>

<%= label_tag 'age', 'Age:'%>
<%= text_field_tag 'corsair[age]'%>

<%= submit_tag "Je m'inscris"%>

<%end%>

app/views/corsairs/show.html.erb
<h1><%=@corsair.firstname%></h1>
<h2><%=@corsair.age%></h2>

<%= link_to "Changer mes informations", edit_corsair_path, class: "btn btn-lg btn-primary"%>

<%= link_to "Valider", corsairs_path, class: "btn btn-lg btn-success"%>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil",   '#' %></li>
        <li><%= link_to "Index des moussaillons",   '#' %></li>
        <li><%= link_to "Nouveau moussaillon", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpMoussaillons</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", new_corsair_path, class: "btn btn-lg btn-primary"%>

</div>